name: mlws
channels:
  - conda-forge
dependencies:
  - python=3.10
  - accelerate
  - adversarial-robustness-toolbox
  - agate
  - aim
  - albumentations
  - allennlp
  - altair
  - arviz
  - auto-sklearn
  - autograd
  - ax-platform
  - black
  - bokeh
  - botorch
  - bqplot
  - captum
  - catboost
  - category_encoders
  - chainer
  - coremltools
  - cupy
  - dash
  - dask
  - datasette
  - datashader
  - dedupe
  - deepspeed
  - distributed
  - dm-haiku
  - dowhy
  - dtale
  - dtreeviz
  - dvc
  - einops
  - emcee
  - face_recognition
  - fairscale
  - fairseq
  - faiss
  - featuretools
  - filterpy
  - fiona
  - flax
  - folium
  - gensim
  - geopandas
  - geopy
  - gluonts
  - gpflow
  - gpustat
  - gpytorch
  - gym
  - hdbscan
  - hmmlearn
  - hnswlib
  - holoviews
  - imageai
  - imagehash
  - imageio
  - imbalanced-learn
  - implicit
  - ipyleaflet
  - ipykernel
  - jaxlib
  - jellyfish
  - jina-core
  - keras
  - keras-tuner
  - kornia
  - librosa
  - lifelines
  - lightfm
  - lightgbm
  - matplotlib
  - metaflow
  - missingno
  - mlflow
  - mlxtend
  - mne
  - monai
  - moviepy
  - mpld3
  - mxnet
  - networkx
  - nltk
  - nmslib
  - ocrmypdf
  - onnx
  - opacus
  - optimum
  - optuna
  - pandas-ta
  - pennylane
  - pillow
  - plotly
  - plotnine
  - pmdarima
  - prophet
  - pycaret
  - pydeck
  - pydub
  - pyjanitor
  - pyldavis
  - pymc3
  - pyod
  - pyqtgraph
  - pyro-ppl
  - pyspark
  - pytesseract
  - python-annoy
  - python-flair
  - python-graphviz
  - pythran
  - pytorch
  - pytorch_geometric
  - pytorch-ignite
  - pytorch-lightning
  - pytorch-metric-learning
  - pyvista
  - rasterio
  - ray-all
  - sacred
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - sentence-transformers
  - sentencepiece
  - shap
  - shapely
  - skorch
  - sktime-all-extras
  - sonnet
  - spacy
  - spacy-transformers
  - speechrecognition
  - spleeter
  - stanza
  - statsforecast
  - statsmodels
  - stumpy
  - sympy
  - ta
  - tensorboard
  - tensorboardx
  - tensorflow
  - tensorflow-datasets
  - tensorflow-hub
  - tensorflow-probability
  - tensorly
  - textacy
  - textblob
  - theano
  - thinc
  - timm
  - tokenizers
  - torchdiffeq
  - torchmetrics
  - torchvision
  - transformers
  - tsfresh
  - tslearn
  - tts
  - umap-learn
  - vispy
  - vowpalwabbit
  - wand
  - wandb
  - wordcloud
  - xgboost
  - yfinance
