name: mlws
channels:
  - conda-forge
dependencies:
  - python=3.10
  - tensorflow
  - scikit-learn
  - matplotlib
  - pytorch
  - scipy
  - transformers
  - pillow
  - sympy
  - pyspark
  - keras
  - nltk
  - opencv=4
  - ipykernel=6
  - ray-all
  - plotly
  - tensorboard
  - accelerate
  - av
  - ipywidgets
  - matplotlib
  - pytorch-lightning
  - diffusers
  - peft
  - black
  - mlflow
  - networkx
  - sentencepiece
  - langchain
  - gradio
  - timm
  - onnxruntime
  - datasets
  - evaluate
  - gluonts
  - ujson
  - networkx
  - keras
  - imageio
  - spacy
# simulate
