name: mlws
channels:
  - conda-forge
dependencies:
  - python=3.10
  - scikit-learn
  - matplotlib
  - pytorch
  - scipy
  - transformers
  - sympy
  - ipykernel=6
  - ray-all
  - plotly
  - tensorboard
  - accelerate
  - av
  - ipywidgets
  - lightning
  - diffusers
  - peft
  - black
  - mlflow
  - networkx
  - sentencepiece
  - gradio
  - timm
  - onnxruntime
  - datasets
  - evaluate
  - gluonts
  - ujson
# simulate
