poetry add tensorflow
poetry add scikit-learn
poetry add matplotlib
poetry add torch
poetry add scipy
poetry add transformers
poetry add Pillow
poetry add sympy
poetry add statsmodels
poetry add pyspark
poetry add keras
poetry add nltk
poetry add scikit-image
poetry add spacy
poetry add xgboost
poetry add ray
poetry add seaborn
poetry add networkx
poetry add tensorboard
poetry add dask
poetry add lightgbm
poetry add jax
poetry add torchvision
poetry add bokeh
poetry add pydeck
poetry add plotly
poetry add pytorch-lightning
poetry add paddlepaddle
poetry add altair
poetry add gensim
poetry add dash
poetry add onnx
poetry add dvc
poetry add rasa
poetry add streamlit
poetry add mlflow
poetry add catboost
poetry add distributed
poetry add fastai
poetry add optuna
poetry add flair
poetry add gym
poetry add folium
poetry add yfinance
poetry add wandb
poetry add gradio
poetry add pymc3
poetry add jina
poetry add pymilvus
poetry add cupy
poetry add mxnet
poetry add imageio
poetry add moviepy
poetry add geopandas
poetry add theano
poetry add shap
poetry add rasterio
poetry add sagemaker
poetry add deepspeed
poetry add horovod
poetry add dgl
poetry add torch-geometric
poetry add timm
poetry add mmdet
poetry add shapely
poetry add pycaret
poetry add pyecharts
poetry add flax
poetry add mne
poetry add sktime
poetry add pymilvus
poetry add tensorflow-probability
poetry add tensorflow-datasets
poetry add vowpalwabbit
poetry add apache-flink
poetry add thinc
poetry add fiona
poetry add metrics
poetry add accelerate
poetry add kornia
poetry add fairseq
poetry add pyqtgraph
poetry add nni
poetry add spark-nlp
poetry add fiftyone
poetry add holoviews
poetry add fbprophet
poetry add textblob
poetry add sentencepiece
poetry add albumentations
poetry add tensorflow-addons
poetry add mlxtend
poetry add arviz
poetry add allennlp
poetry add pyod
poetry add pyvista
poetry add paddleocr
poetry add triton
poetry add bentoml
poetry add monai
poetry add speechbrain
poetry add torchtext
poetry add carla
poetry add tensorflow-hub
poetry add insightface
poetry add torchaudio
poetry add textacy
poetry add recommenders
poetry add graphviz
poetry add pydub
poetry add imbalanced-learn
poetry add wand
poetry add opencv-python
poetry add einops
poetry add umap-learn
poetry add sentence-transformers
poetry add jellyfish
poetry add tensorflow-text
poetry add category_encoders
poetry add plotnine
poetry add geopy
poetry add keras-tuner
poetry add stanza
poetry add pyro-ppl
poetry add featuretools
poetry add deepface
poetry add vispy
poetry add autokeras
poetry add adversarial-robustness-toolbox
poetry add tokenizers
poetry add azureml-sdk
poetry add nemo-toolkit
poetry add tts
poetry add tensorboardX
poetry add autograd
poetry add pyldavis
poetry add chainer
poetry add annoy
poetry add datashader
poetry add snakemake
poetry add librosa
poetry add gpytorch
poetry add datasette
poetry add tf-agents
poetry add dm-sonnet
poetry add wordcloud
poetry add SpeechRecognition
poetry add pytorch-metric-learning
poetry add botorch
poetry add clearml
poetry add metaflow
poetry add ax-platform
poetry add interpret
poetry add dedupe
poetry add neuralprophet
poetry add netron
poetry add face_recognition
poetry add tensorflow-model-optimization
poetry add pmdarima
poetry add coremltools
poetry add easyocr
poetry add sacred
poetry add emcee
poetry add visualdl
poetry add bayesian-optimization
poetry add agate
poetry add fairscale
poetry add lifelines
poetry add dm-haiku
poetry add captum
poetry add pythran
poetry add pgmpy
poetry add spleeter
poetry add auto-sklearn
poetry add bqplot
poetry add h2o
poetry add tsfresh
poetry add pennylane
poetry add pytorch-ignite
poetry add arcgis
poetry add tfx
poetry add torchserve
poetry add missingno
poetry add ImageHash
poetry add ipyleaflet
poetry add hdbscan
poetry add hmmlearn
poetry add lightfm
poetry add pytesseract
poetry add spacy-transformers
poetry add nmslib
poetry add tslearn
poetry add gpflow
poetry add ocrmypdf
poetry add hnswlib
poetry add tensorly
poetry add ktrain
poetry add stumpy
poetry add pyjanitor
poetry add imageai
poetry add dowhy
poetry add tensorflow-recommenders
poetry add aim
poetry add optimum
poetry add gluonts
poetry add gpustat
poetry add mpld3
poetry add pandas-ta
poetry add filterpy
poetry add ta
poetry add evaluate
poetry add torchdiffeq
poetry add implicit
poetry add skorch
poetry add dtreeviz
poetry add dtale
poetry add opacus
poetry add statsforecast
poetry add facets-overview
poetry add autogluon
poetry add synapseml