[tool.poetry]
name = "mlws"
version = "0.1.0"
description = "A Machine Learning Workspace"
authors = ["LizeLive <git@lize.live>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
torch = "^2.0.0"
torchvision = "^0.15.1"
torchaudio = "^2.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
