name: mlws
channels:
  - pytorch
  - nvidia
  - pytorch3d
  - conda-forge
dependencies:
  - python>=3.10
  - pytorch-cuda=11.8
  - scikit-learn
  - matplotlib
  - pytorch=2
  - scipy
  - transformers
  - pillow
  - sympy
  - pyspark
  - nltk
  - opencv=4
  - ipykernel=6
  - ray-all
  - plotly
  - tensorboard
  - accelerate
  - av
  - ipywidgets
  - pytorch-lightning
  - diffusers
  - peft
  - black
  - mlflow
  - networkx
  - sentencepiece
  - gradio
  - timm
  - onnxruntime
  - datasets
  - evaluate
  - gluonts
  - ujson
  - networkx
  - keras
  - imageio
  - spacy
  - pip
  - gymnasium
  - boost
  - cmake
  - wikipedia
  - sparqlwrapper
  - sentence-transformers
  - sdl2
  - numba # does not support 3.11
  - pytorch3d # does not support 3.11
  # - detectron2 # does not support 3.0
  # - langchain # does not support torch 2
  - pip: 
    - vizdoom # had to install some system deps
  #   # can't install via conda for some reaoson
  #   # apt install cmake git libboost-all-dev libsdl2-dev libopenal-dev
  #   # - git+https://github.com/mwydmuch/ViZDoom.git
  #   - envpool
  #   - pywikibot
  #   - git+https://github.com/facebookresearch/detectron2@main#subdirectory=projects/DensePose